name: Test package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  run-package-tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install package
        run: python setup.py install
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: python -m pytest -rA tests
