name: Test and coverage package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  test-and-coverage-package:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install package
        run: python -m pip install -e .

      - name: Run tests
        run: python -m pytest -rA tests

      - name: Run coverage
        run: python -m pytest --cov=src --cov-report html:cov_html tests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cov_html
